# Generated by Django 4.2.4 on 2023-09-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='passoword',
            field=models.CharField(max_length=255),
        ),
    ]
